sudo: required
services:
  - docker

before_install:
  - docker build -t ryhshu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ryhshu/react-test npm test -- --coverage

after_success:
  - docker build -t ryhshu/multi-client ./client
  - docker build -t ryhshu/multi-nginx ./nginx
  - docker build -t ryhshu/multi-server ./server
  - docker build -t ryhshu/multi-worker ./worker
#Log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
  - docker push ryhshu/multi-client
  - docker push ryhshu/multi-nginx
  - docker push ryhshu/multi-server
  - docker push ryhshu/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-233654046809
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY